# Generated by Django 3.1.3 on 2020-11-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='useEvent',
            new_name='userEvent',
        ),
    ]
