# Generated by Django 3.1.3 on 2020-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detail_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='events/maccho.png', null=True, upload_to='events'),
        ),
    ]
