# Generated by Django 3.1.3 on 2020-11-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201128_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='胸', max_length=10),
            preserve_default=False,
        ),
    ]
